import type { CSSProperties } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import { getSiteThemeSettings } from "@/lib/supabase/queries";
import { resolveThemeTokens } from "@/lib/theme/resolve";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// "Modern Koyu" preset'inin font'u (bkz. lib/theme/presets.ts) — hangi
// preset seçili olursa olsun her iki font da build zamanında yükleniyor,
// runtime'da hangisinin kullanılacağına --font-sans değişkeni karar veriyor
// (next/font, font seçimini çalışma zamanı verisine göre şartlı yapmaya
// izin vermiyor). Detay: docs/TEMA-MIMARISI.md "Yeni tema nasıl eklenir".
const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const themeSettings = await getSiteThemeSettings();
  const { dataTheme, styleVars } = resolveThemeTokens(themeSettings);

  return (
    <html
      lang="en"
      data-theme={dataTheme}
      style={styleVars as CSSProperties}
      className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
